name: minfin_one_id
description: OneID orqali autrizatsiya qilish
version: 3.0.5
homepage: https://github.com/nslogx/flutter_easyloading
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter