name: minfin_one_id
description: OneID orqali autrizatsiya qilish
version: 0.0.2
homepage: https://github.com/abbos2101/minfin_one_id
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.0