name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for taking the time to open an issue. I will have a look and answer as soon as possible.'
        pr-message: 'Thank you for opening an PR. I will review the PR and provide feedback as soon as possible.'
